name: Docker Image CI

on:
  workflow_dispatch
jobs:

  build:
    runs-on: winrunner 

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t dockerfile nagarajucts/jmeterwithselenium .
