name: Docker Image CI
on:
 workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Docker Build with CMD
        run: docker build . --file Dockerfile --tag nagarajucts/jmeterwithselenium
        shell: cmd
