name: Docker Image CI
on:
 workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set PowerShell Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
        shell: powershell
      
      - name: Run Docker Build
        run: docker build . --file Dockerfile --tag nagarajucts/jmeterwithselenium
        shell: powershell
